# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod 'WebViewJavascriptBridge', :git => 'https://github.com/stury/WebViewJavascriptBridge.git', :branch => ‘master’
   pod 'Adjust', '~> 4.31.0'
   pod 'Firebase/Messaging', '~> 10.24.0'
   pod 'KeychainSwift', '~> 24.0.0'
   pod 'Alamofire', '~> 5.9.1'
   pod 'HandyJSON', '~> 5.0.2'
   pod 'Firebase/RemoteConfig'
end


# 统一的 post_install 处理
post_install do |installer|
  flutter_engine = File.join(flutter_root, 'bin', 'cache', 'artifacts', 'engine')
  flutter_xcframework = File.join(flutter_engine, 'ios', 'Flutter.xcframework')
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_CONFIGURATION_BUILD_DIR}/Flutter'
      if File.exist?(flutter_xcframework)
        sim_slice = File.join(flutter_xcframework, 'ios-arm64_x86_64-simulator')
        device_slice = File.join(flutter_xcframework, 'ios-arm64')
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << sim_slice if File.exist?(sim_slice)
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << device_slice if File.exist?(device_slice)
      end
      if target.name == 'HandyJSON'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end
